# Generated by Django 4.1.7 on 2023-02-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='نام مشتری')),
                ('customer_family', models.CharField(max_length=30, verbose_name='نام خانوادگی مشتری')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='شماره تماس مشتری')),
                ('customer_birthday', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولد مشتری')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15, verbose_name='نام محصول')),
                ('product_price', models.CharField(max_length=15, verbose_name='نام محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedaad', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('price_all', models.IntegerField(verbose_name='قیمت کل')),
                ('date_sabt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.customer', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
