# Generated by Django 4.1.7 on 2023-02-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_customer_table_alter_orderproduct_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(verbose_name='قیمت محصول'),
        ),
    ]
