# Generated by Django 4.1.7 on 2023-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_customer_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date_sabt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_img', verbose_name='عکس_محصول'),
        ),
    ]
